### ISSUE TITLE
Add /tpaall and /tpall commands

### ISSUE THREAD

**Issue by Uharn** [WiIIiam278/HuskHomes2#103]
This is for animation purpose: an animator would need to ask all player in a bungee network if they want to join the event

The simple way is to simply add a /tpa all command

But it could also be possible to do something very interresting:

/tpaevent all <Animators home name> 
then the player would be asked to teleport to the event home with a message including the home description like

%player% proposed you to teleport to the event: %home_desc%, do you want to participate?
Choose Accept Deny

animators would have some private homes that players could not use except from thoses /tpaevnt command

**Comment by WiIIiam278** [comment]
Here's how I imagine this being done

- /tpall [server]: Teleport all players on your network (or just on the server you are on if the server arg is specified)
- /tpaall [server]: Send a teleport request to all players on your network (or just on the server you are on if the server arg is specified)

**Comment by Uharn** [comment]
it's good! (maybe an optionnal argument "reason" To be able to explain why the TPA?

/tpaall [server] [reason]

Then the reason would be shown as text in the TPA request?
