### ISSUE TITLE
Syncing bed locations

### ISSUE THREAD

**Issue by kneeck** [WiIIiam278/HuskHomes2#111]
Allow player beds cross-server to be synced. 

Player sets bed location on Server A and dies on Server B, re-spawn player to their bed on Server A. If no bed set, send to bungee spawn.

**Comment by justaureus** [comment]
Hey, thanks for the issue!  Sadly this is out of scope for HuskHomes, but would be a good issue to add to HuskSync.

**Comment by WiIIiam278** [comment]
See #123
