### ISSUE TITLE
/tpahere requests complete even if the requester no longer has permission to execute it at teleport time

### ISSUE THREAD

**Issue by iVillager** [WiIIiam278/HuskHomes2#112]
In order to avoid that players can teleport other players everywhere, try to make the /tpahere more safe.
For example: teleport the player that accepted the tpahere in the location where the first player asked to teleport to him. Another solution would be allowing teleport requests only in luckperms contexts: where the teleport permission is true, player 2 goes to the player 1, but if the permission is false, player 2 won't go to the player 1.

**Comment by WiIIiam278** [comment]
Removing the bug label from this because this isn't a bug so much as it is an unintended consequence of contextual permissions which is a LuckPerms feature, not a HuskHomes one (though it should still be accounted f or).

**Comment by WiIIiam278** [comment]
See new mode proposed in #139 to fix this
