### ISSUE TITLE
IllegalStateException when attempting to teleport with a passenger attached

### ISSUE THREAD

**Issue by lucian929** [WiIIiam278/HuskHomes2#125]
When a player has a passenger attached (https://papermc.io/javadocs/paper/1.18/org/bukkit/entity/Entity.html#addPassenger(org.bukkit.entity.Entity), HuskHomes throws an IllegalStateException because it attempts to dismount the passenger async.

https://sentry.io/share/issue/c10e007397a24223926fd4db3870a170/

**Comment by WiIIiam278** [comment]
Seems like this is getting executed asynchronously sometimes, throwing this.
https://github.com/WiIIiam278/HuskHomes2/blob/f9094ec4f6ffa26ed0f6143d5e7f31c45a0d3fe5/src/main/java/me/william278/huskhomes2/teleport/TeleportManager.java#L96
