### ISSUE TITLE
Have HuskHomes track and restrict teleportation to possible target players cross-server and allow them to appear in TAB completion for teleport commands.

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#13]
Players can do /tpa <random gibberish here> and still send a tp request (or at least chat displays the "request sent to ...". Probably should have an error if the player isn't online anymore or doesn't actually exist.

**Comment by WiIIiam278** [comment]
Known issue, would require a solution such that HuskHomes is able to keep track of all players who are eligable to be TP'd to across all servers (i.e those who are on servers with HuskHomes installed).
The solution would be to send a plugin message between servers requesting player lists. HuskHomes would send a plugin message out updating servers when a player has joined or left. Upon receiving this message all HH servers would request player lists from other servers and compile them together to determine the list of online players. This could then be used for TAB completion and determining if a teleport request is valid cross-server.
The other solution would be to implement a bungee plugin to do this, but that's not worthwhile or practical.

**Comment by WiIIiam278** [comment]
Partially implemented; doesn't restrict players you can teleport to but it now updates a tab list every 60 seconds (configurable/toggle-able). Closing for now.
