### ISSUE TITLE
Re-implement the EssentialsX migrator

### ISSUE THREAD

**Issue by Ekmot276** [WiIIiam278/HuskHomes2#132]
A user reported he had some issues with using the EssentialsX-Migrator with HuskHomes and reported the following error:

`[22:27:30 WARN]: [HuskHomes] ? Could not migrate home as the world value was a UUID and is not loaded on this server.`

He also provided this issue from [EssentialsX](https://github.com/EssentialsX/Essentials/issues/4342) itself, but I'm not sure if it's related or not and included it only for reference.

**Comment by WiIIiam278** [comment]
One user did this fix which works for them
https://github.com/minecraftexperienceserv/HuskHomes2/commit/f9a6f16ab10ae8a27d616b62d588aa344a8633a0
I think that the plugin should probably use Essentials' API rather than reading the files. Probably.
