### ISSUE TITLE
Deletion of a world containing homes will only delete the location, not the home itself

### ISSUE THREAD

**Issue by justaureus** [WiIIiam278/HuskHomes2#133]
This issue may pertain to mySQL as well, but this specific instance was only spotted on a setup using SQLite.  

Steps to reproduce are as follows:
* Setup a server running HuskHomes, with the SQLite database type
* Set some homes within a world within this server
* Delete the world from the server
* View the DB file
* Once within the DB file navigate to any home created within the deleted world
* The home will remain (when it should have been deleted), however, within the locations table lookup the location ID associated with the home
* The location ID of that home will be missing, causing an ``java.lang.IllegalArgumentException: Could not return a teleportationPoint from the locations data table`` exception

**Comment by WiIIiam278** [comment]
This isn't really a bug so much as it is a fact of what will happen when worlds are deleted. However, this error should be caught and an error message displayed along the lines of "Failed to teleport you as the world could not be found." - the home should then be automatically deleted.
