### ISSUE TITLE
[add world tp] world tp via other plugins, cannot use back

### ISSUE THREAD

**Issue by From-pErfo** [WiIIiam278/HuskHomes2#142]
Can't go back to previous position when I use other plugins for world tp
I wish to add world tp to function or Capture tp from other plugins (If can
thanks

I have another question, the plugin will be slow to respond on any tp, I use SQLite, don't know if the problem is from my device
This will last for a few seconds, sometimes with SQL Error

**Comment by Ekmot276** [comment]
Hm, have you a bungeecord/waterfall setup with multiple servers on different machines/locations? Please also provide the SQL errors.

Regarding your first question I don't think I got your point there...

**Comment by WiIIiam278** [comment]
> Can't go back to previous position when I use other plugins for world tp
I wish to add world tp to function or Capture tp from other plugins

This isn't something that will be supported, sorry.
Regarding your SQL issues, that's a separate issue, you may need to perform some diagnostics there.
