### ISSUE TITLE
Cross server teleport sometimes fails to finish when a player joins their destination server

### ISSUE THREAD

**Issue by Ekmot276** [WiIIiam278/HuskHomes2#143]
**Specs**
- Java 16 
- Paper 1.17.1
- Latest version of HuskHome
- SQL 
- Redis

**Issue:**
Teleport commands as /warp, /spawn, /home, /tpa, /back, etc are not teleporting to the destination but to the previous location. Only when its cross-server teleport. Its a random behaviour, does not happens always.
Example: I sethome in **server1-overworld** at coords 100 100 100, after that i walk to coords 500 100 500. Then, i do /spawn that will send me to the **spawn-server**. And finally, i execute /home and i will be teleported to **server1-overworld** but to coords 500 100 500 instead of teleporting me to my home-> coords 100 100 100.

**Expected behaviour**
To actually teleport where it suppose to.

**Comment by WiIIiam278** [comment]
To clarify it seems some commands won't finish their teleport when the player has joined the target server

**Comment by msmanui** [comment]
Yeah, it is also ocurring to me.

**Comment by notrazer40** [comment]
I can relate to this, as well is happening to me.

**Comment by WiIIiam278** [comment]
Can this be reproduced on vanilla spigot where Paperlib isn't used?

**Comment by notrazer40** [comment]
> Can this be reproduced on vanilla spigot where Paperlib isn't used?
Sorry, i cant really test that as i would kill the server in terms of performance if i setup with Spigot.

**Comment by WiIIiam278** [comment]
apparently not fixed

**Comment by WiIIiam278** [comment]
Closing this for now as there's noting really to track here; I'm unable to reproduce this issue. This can be reopened if this persists after the v3 rewrite
