### ISSUE TITLE
/tp only works for the first player to run the command

### ISSUE THREAD

**Issue by AGP333** [WiIIiam278/HuskHomes2#153]
Plugin version since a0ce0dc52a7b8522269b6594d91973d2d924b5a6 and Paper 1.18.1 (Build 129)

When you /tp to another player, it's being run correctly for whoever was the first person to use the command
All players using /tp after will run the command for the first player who ran the command
Restarting the server makes the loop start over - Makes it work for the first player who teleports.

Gif of the issue https://cdn.discordapp.com/attachments/931671759860695130/945431174560485446/o5CcAinrBg.gif

**Comment by WiIIiam278** [comment]
Closing this for now as its to do with an indev version and will be resolved in v3 :-)
