### ISSUE TITLE
Don't register commands that are disabled

### ISSUE THREAD

**Issue by magrigry** [WiIIiam278/HuskHomes2#154]
RTP command is still registered even when disabled. If we use another RTP, it may not work even with HuskHome RTP disabled because HuskHome will handle the command.

**Comment by WiIIiam278** [comment]
yeah fair enough, commands are registered all through the yaml right now, should probably not register it and do so programmaticly for v3

**Comment by WiIIiam278** [comment]
This is actually not possible without doing hacky commandmap manipulation or switching to a command library. Paper is changing up some API stuff to make this better in the future, but closing this for now. v3 has a nicer way of disabling commands, though
