### ISSUE TITLE
Allow teleportPlayer to teleport a player without calling setPlayerLastPosition

### ISSUE THREAD

**Issue by magrigry** [WiIIiam278/HuskHomes2#155]
It would be usefull to be able to call teleportPlayer method through the API without saving last location. A plugin may want to teleport a player without saving player's last position. 

e.g. `public void teleportPlayer(Player player, TeleportationPoint point, boolean timed, bool saveLastLocation) `

**Comment by WiIIiam278** [comment]
Fixed in #323 
`TeleportBuilder` provides a way of specifying whether to update the last position.
