### ISSUE TITLE
Add UTF-8 encoding support for home name

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#156]
Whether utF-8 encoding support can be added for home name.

Some people may need this, and unsupported languages will make their home name look like an unknown variable in the code.

I know that the home description supports UTF-8 coding, but it is not as obvious as the name.

If it really doesn't support it at all, please turn off this problem. Sorry to trouble.

**Comment by WiIIiam278** [comment]
It’s something that’s been raised before, the reason it’s not present currently is more of a design decision than anything else; Unicode can cause some funkiness with people using annoying characters and emoji in home names. I agree though it’s not great for international users. Adding an option for this in 3.0 would be good.

**Comment by From-pErfo** [comment]
thank you very much
Other plugins I've seen can use regex to filter those special characters, and the regex configuration seems reasonable

**Comment by WiIIiam278** [comment]
Added in v3 <3 New config option
