### ISSUE TITLE
config option to toggle public home / permission node issue

### ISSUE THREAD

**Issue by Ceddix** [WiIIiam278/HuskHomes2#157]
Since the `huskhomes.publichome` doesn't remove the `[Make Public]/[Make Private]` options from the `/edithome` messages, there should be a config option to disable public homes completely or/and the `[Make Public]/[Make Private]` options shouldn't be displayed, if the permission node is set to `false`.

**Comment by WiIIiam278** [comment]
Not sure why this has been in the feature request pile for so long, seems like a pretty obvious oversight.
