### ISSUE TITLE
Plugin gets stuck while checking for updates

### ISSUE THREAD

**Issue by From-pErfo** [WiIIiam278/HuskHomes2#166]
*It's very noticeable because of my poor network*
With update checking turned on, the plugin will always get stuck at startup, with no errors and no response
`[HuskHomes] Enabling HuskHomes v2.11.2`

Sometimes it gets stuck for tens of seconds, sometimes it keeps stuck here

**Comment by WiIIiam278** [comment]
Disable update checking in the config file. Not an issue.
