### ISSUE TITLE
Add option so that /sethome will overwrite existing homes

### ISSUE THREAD

**Issue by TechRoot** [WiIIiam278/HuskHomes2#168]
**Make /sethome command to automatically replace default home location.**

Currently, /sethome fails to set a home if a HOME location is already set, so you need to perform /delhome home and then /sethome
In servers where a rank/group can only have one home, this scheme fails to be appropiate, as they prefer to simply overwrite their home, instead of editing it.

This may be included as an option, inside settings.yml

**Comment by dmptrluke** [comment]
This one would be a great addition for me too!
