### ISSUE TITLE
"`moved too quickly!`" in spigot console during large-distance teleports.

### ISSUE THREAD

**Issue by From-pErfo** [WiIIiam278/HuskHomes2#172]
I've found that any teleportation over a certain distance will trigger moved too quickly! This distance depends on the value set in spigot.yml.settings.moved-too-quickly-multiplier
Is this caused by a misconfiguration? It should be common, but I can't find other Issues.

**Comment by WiIIiam278** [comment]
This is just a spigot thing:tm: unfortunately. No way of working around this to my knowledge.

**Comment by Boy0000** [comment]
This can be fixed on Paper with their PlayerFailMoveEvent
https://jd.papermc.io/paper/1.20.1/io/papermc/paper/event/player/PlayerFailMoveEvent.html
Was added in 1.20 so it will not apply below

<img width="678" height="186" alt="Image" src="https://github.com/user-attachments/assets/18bf8fb3-df87-464a-a273-f7098a2f9e76" />
