### ISSUE TITLE
/back command using random_teleport int costs when user has bypass permissions.

### ISSUE THREAD

**Issue by TechRoot** [WiIIiam278/HuskHomes2#174]
If a user has the huskhomes.bypass timers node, Huskhomes will use random_teleport: int costs instead of back: int costs.

https://i.imgur.com/x1vvwQy.png
https://i.imgur.com/yegmlL9.png

**Comment by WiIIiam278** [comment]
Caused by this line
https://github.com/WiIIiam278/HuskHomes2/blob/master/src/main/java/me/william278/huskhomes2/teleport/TeleportManager.java#L208
