### ISSUE TITLE
Update squaremap integration

### ISSUE THREAD

**Issue by Ekmot276** [WiIIiam278/HuskHomes2#175]
A user reported the integration of husksync into squaremap throws the following error which might has been caused by an api update at squaremap:

> [07:01:45 ERROR]: Error occurred while enabling HuskHomes v2.11.2 (Is it up to date?)
> java.lang.NoSuchMethodError: 'java.lang.String xyz.jpenilla.squaremap.api.MapWorld.name()'
>         at me.william278.huskhomes2.integrations.map.SquareMap.loadWorld(SquareMap.java:150) ~[HuskHomes-2.11.2.jar:?]
>         at me.william278.huskhomes2.integrations.map.SquareMap.initialize(SquareMap.java:98) ~[HuskHomes-2.11.2.jar:?]
>         at me.william278.huskhomes2.HuskHomes.onEnable(HuskHomes.java:223) ~[HuskHomes-2.11.2.jar:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:535) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1612]
>         at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1612]

**Comment by yashendra2797** [comment]
Please let me know if I can help in any way. Thanks!

**Comment by WiIIiam278** [comment]
> Please let me know if I can help in any way. Thanks!

You're more than welcome to PR a fix that updates the API :-)

**Comment by WiIIiam278** [comment]
Closing this for now, probably in favor of Pl3xMap v2 when that matures
