### ISSUE TITLE
Home limit permissions of the same value don't stack

### ISSUE THREAD

**Issue by Dakotaa** [WiIIiam278/HuskHomes2#176]
With home limit permission stacking enabled, if a player has two groups that both have the same limit permission (e.g. 2), the player will only get one of those, and have a maximum of 2 homes instead of 4.

**Comment by WiIIiam278** [comment]
Workaround is to grant permissions prefixed with 0 - which will stack
e.g. huskhomes.max_homes.01

**Comment by WiIIiam278** [comment]
Basically the only way to solve this is with a manual hook to something like LuckPerms. Given that this is a relatively remote feature, I don't think it's worth it to be honest for just this one hook, especially as that solution wouldn't work for other permission plugins (even though LP is totally the standard).
