### ISSUE TITLE
add a PlayerBack API Event

### ISSUE THREAD

**Issue by emmanuelvlad** [WiIIiam278/HuskHomes2#180]
It would be nice to be able to cancel a PlayerBackEvent.

Ex:
Not allowing /back to a specific location

**Comment by WiIIiam278** [comment]
Added to the backlog for API v3 👍

**Comment by WiIIiam278** [comment]
There's a new TeleportEvent that lets you do this technically, though I suppose there's no specific way to see the source of the teleport (i.e. to see if it was a /back). What's the use case?

**Comment by emmanuelvlad** [comment]
> There's a new TeleportEvent that lets you do this technically, though I suppose there's no specific way to see the source of the teleport (i.e. to see if it was a /back). What's the use case?

Blocking the ability to /back in specific regions/player's island

**Comment by WiIIiam278** [comment]
> > There's a new TeleportEvent that lets you do this technically, though I suppose there's no specific way to see the source of the teleport (i.e. to see if it was a /back). What's the use case?
> 
> Blocking the ability to /back in specific regions/player's island

Have you looked at LuckPerms' contextual permissions that let you deny nodes depending on circumstances such as world, location, metadata etc?

**Comment by emmanuelvlad** [comment]
It's more about blocking the ability of being teleported back to specific regions, not blocking the usage of it
