### ISSUE TITLE
Want to update a Prefix in the language file 

### ISSUE THREAD

**Issue by SnivyJ** [WiIIiam278/HuskHomes2#185]
can you add a “Prefix” option such as 
Prefix: '[HuskHomes](#ff3300) ' 
The content in prefix will be added in front of the text output
look like [HuskHomes] you dont have permission to do that

**Comment by WiIIiam278** [comment]
The reason I don't do this is because I think it's better to let you customize each line individually rather than with bulk options.
You can just add [HuskHomes] at the start of every line, if you want. Use find and replace to do this quickly.
