### ISSUE TITLE
Global re-spawning: Allow re-spawning to global spawn rather than local spawn if bed not defined

### ISSUE THREAD

**Issue by Ceddix** [WiIIiam278/HuskHomes2#223]
Currently, if a player does not have a global respawn point, he respawns at the respawn point of his current server _(which is either a bed or the spawn of this server)_.
Therefore, I thought it would be nice if you could, for example, select that you respawn at the global spawn in this case.

**Comment by WiIIiam278** [comment]
Duplicate of #279
