### ISSUE TITLE
RTP cooldown is seemingly ineffective

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#224]
I can't find the rtp cooldown in config.yml, is it canceled?
`cooldown_length` No effect. 
Also, there is no config.yml comment in the wiki page.

**Comment by WiIIiam278** [comment]
`rtp.cooldown_length` is the key -- what do you mean by "no effect"?

**Comment by ApliNi** [comment]
The default value of `rtp.cooldown_length` is 10, but the player can reuse the command very quickly. 
I only assign these permissions to players: 
```
huskhomes.home: true
huskhomes.sethome: true
huskhomes.delhome: true
huskhomes.delhome.all: true
huskhomes.edithome: true
huskhomes.warp: true
huskhomes.back: true
huskhomes.tprequest: true
huskhomes.spawn: true
```

**Comment by WiIIiam278** [comment]
Hmm, okay - will need to look at that

**Comment by ApliNi** [comment]
> @ApliNi could you clarify, you're just using base /rtp -- because the cooldown won't apply if you're /rtp-ing another user or via console.

It's used by players in the game. Can't reproduce it on your side?
