### ISSUE TITLE
Distinguish between the homeName in the command and the homeName escaped for MD

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#241]
![image](https://user-images.githubusercontent.com/59365724/193437057-26c2b687-6d24-40ea-9c93-064f59e01263.png)

Home Name: `[112]`.

**Comment by WiIIiam278** [comment]
Okay -- yeah indeed if you enable Unicode names and use MineDown formatting characters I guess that does happen.

I'm a bit confused why someone would want to make their home name [118] lol but sure this is an oversight

**Comment by ApliNi** [comment]
solve this problem with `/home <uuid>`, Do you think?

**Comment by ApliNi** [comment]
> PRs welcome.

Sorry, I haven't touched java at all 😐

**Comment by ApliNi** [comment]
Perhaps there is an easy way to do this, `/home <user>.<home_uuid> -uuid`, Distinguish between names and uuid patterns by adding the "-uuid" parameter at the end
