### ISSUE TITLE
Teleport strange behaviour with tabcomplete name event

### ISSUE THREAD

**Issue by iVillager** [WiIIiam278/HuskHomes2#246]
Version: 3.0.4 from [spigot](https://www.spigotmc.org/resources/%E2%AD%90-huskhomes-1-16-1-19-%E2%AD%90-simple-intuitive-teleportation-suite-with-cross-server-support.83767/updates)

Using REDIS as messanger_type.

With this messenger_type we found a strange behaviour in tabcompleting names.
1. /tp and /tpa are ok if you are in two separate servers
2. /tp and /tpa player list is taken from the global player list instead of the player list from the servers with REDIS cache (I think it's normal because of this
`    public CompletableFuture<List<String>> updatePlayerListCache(@NotNull HuskHomes plugin, @NotNull OnlineUser requester) {
        if (plugin.getSettings().crossServer) {
            return plugin.getNetworkMessenger().getOnlinePlayerNames(requester).thenApply(returnedPlayerList -> {
                players.clear();
                players.addAll(List.of(returnedPlayerList));
                return players;
            });
        } else {
            players.clear();
            players.addAll(plugin.getOnlinePlayers()
                    .stream()
                    .filter(player -> !player.isVanished())
                    .map(onlineUser -> onlineUser.username)
                    .toList());
            System.out.println(String.join(", ", players));
            return CompletableFuture.completedFuture(players);
        }
    }`
    
3. The biggest problem comes when you are both in the same server: /tp and /tpa doesn't tab complete the player names in the same server. Only if you first write his name and teleport to him, the second time both commands work as defined.

**Comment by WiIIiam278** [comment]
Fixed in #323 (I think? This issue's a little weirdly written)
