### ISSUE TITLE
`GUI: Use: Teleport...` The display does not have permissions, but can be used normally

### ISSUE THREAD

**Issue by ApliNi** [WiIIiam278/HuskHomes2#252]
player permissions: 
```
huskhomes.command.home: true
huskhomes.command.sethome: true
huskhomes.command.delhome: true
huskhomes.command.edithome: true
huskhomes.command.warp: true
huskhomes.command.back: true
huskhomes.command.tprequest: true
huskhomes.command.spawn: true
```

Config: default

1. `/home`
2. Click a home
3. Click Teleport

display: `error_no_permission: '[Error:](#ff3300) [You do not have permission to execute that command.](#ff7e5e)'`
Teleport: Normal to continue

**Comment by WiIIiam278** [comment]
Not GUI related, but base plugin related I think.

**Comment by ApliNi** [comment]
yes, The problem is /home `<player>.`<home>.
