### ISSUE TITLE
Unable to use /tp command while vanished

### ISSUE THREAD

**Issue by mredoo** [WiIIiam278/HuskHomes2#255]
If i'm vanished I can't teleport to other players.
![image](https://user-images.githubusercontent.com/98414569/198828246-7d8b6eb9-1ee7-4c0d-86d8-6c59bf66cceb.png)

**Comment by WiIIiam278** [comment]
Regression from 3.x due to new teleportation logic. The filter against vanished players from the pool of teleportation users should be ignored for self-teleports

**Comment by WiIIiam278** [comment]
@mredoo Could you test this with build https://github.com/WiIIiam278/HuskHomes2/commit/e20dcc4ce4eaf7201f16cb0e01c9c03756e34b87 (available on https://modrinth.com/plugin/huskhomes/versions)
