### ISSUE TITLE
Clicking items in certain containers causes HuskHomesGUI interactions to activate at random

### ISSUE THREAD

**Issue by mredoo** [WiIIiam278/HuskHomes2#256]
If I spam click on a block in a dispenser I get teleported to my home/a warp.
![image](https://user-images.githubusercontent.com/98414569/198828369-c0e1e3af-6d7e-4fb3-9edf-0f5542ca75c0.png)

**Comment by WiIIiam278** [comment]
You _might_ have discovered a really obscure library bug... Could you outline some steps to reproduce @mredoo? Like, does spam-clicking items in any random dispenser act as though you've clicked to teleport in a HuskHomesGUI menu? Please include your GUI and HuskHomes versions.

Cheers.

**Comment by mredoo** [comment]
Huskhomes 3.1 and gui 2.0.1, yeah if you spam click act like if you have clicked on a menu

**Comment by Domzzo** [comment]
Some delay, but here is my report as well, as discused with William at discord.

- I have the 3 second warmup set but when the bug happened there was no warmup, no messages or logs in console,
- 3 second warmup still worked when clicking inside GUI,

**Comment by WiIIiam278** [comment]
potentially fixed in 2.1?

**Comment by WiIIiam278** [comment]
no further reports of this since 2.1; closing
