### ISSUE TITLE
`/rtp` will often place players inside of blocks

### ISSUE THREAD

**Issue by RhythmicSys** [WiIIiam278/HuskHomes2#263]
`/rtp` often places players inside of blocks, and occasionally in the air
This has happened to me personally around 3 times in the past week, and have had multiple reports from players.
I currently have no relevant logs available

**Version:** v3.1.1-88802db
**Server Version:** git-petal-"032a81b" (MC: 1.19.2)

**Comment by WiIIiam278** [comment]
Yeah, there's a flaw with the current random teleport logic. Needs another pass. Thanks
