### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by Miriam0** [WiIIiam278/HuskHomes2#268]
![image](https://user-images.githubusercontent.com/46651542/204050449-aed01d56-b5d8-468a-9c93-da4fc67a4d00.png)

**Comment by WiIIiam278** [comment]
If you're not already, please try with the latest modrinth build. I can't really reproduce this
https://modrinth.com/plugin/huskhomes/versions

**Comment by WiIIiam278** [comment]
No further response, closing for now
