### ISSUE TITLE
Restricted warp not available despite permission

### ISSUE THREAD

**Issue by Lorias-Aegorin** [WiIIiam278/HuskHomes2#277]
The player has permission for warping and to the restricted warp. At /warps it is said that no warps are set and if the player tries to warp there anyway, it is said that he has no permission.

Granted permissions:
huskhomes.command.warp
huskhomes.command.warp.spawn

Im using Paper 1.19.2, Java 17, Huskhomes v3.2.1-ed58779

**Comment by WiIIiam278** [comment]
> huskhomes.command.warp.spawn
The name of your spawn warp was probably 'Spawn', with an upper case S. There was a bug that meant the expected case-sensitive permission node was `huskhomes.command.warp.Spawn` as a result. The latest dev build should now automatically ensure the node is in lower case.
