### ISSUE TITLE
Global respawn doesn't take players to global spawn if they have no bed position

### ISSUE THREAD

**Issue by Sixsoul** [WiIIiam278/HuskHomes2#279]
So as discussed with William on discord I was really hoping that when a player dies they can respawn at the /setspawn location, even cross server. Currently it seems that if a player doesn't have a bed or respawn anchor it just sends them to a location on their **current server**, instead of sending them cross server to the spawn point.

**Comment by WiIIiam278** [comment]
Essentially if global respawn is enabled it should move the user to that if they don't have a bed spawn point and global respawn is enabled? maybe a config option to alter this behaviour.

**Comment by WiIIiam278** [comment]
Added in #323
