### ISSUE TITLE
Double Message when warping from console

### ISSUE THREAD

**Issue by Log1x** [WiIIiam278/HuskHomes2#29]
![Screenshot](https://i.imgur.com/10pQ4xU.png)

Currently throwing two messages when doing a warp from console. The first one shouldn't be fired.

**Comment by WiIIiam278** [comment]
HuskHomes fires two messages when doing a console teleport; 
* `teleporting_complete`: '&aYou have been teleported!'  
* `teleporting_complete_console`: '&7(Console teleported you to %1%)'

If you'd just like one of them to fire, you could blank out the `teleporting_complete_console` string to say nothing; I may change the behaviour such that the latter string is the only one to fire but for the time being this works as intended.
