### ISSUE TITLE
Can't teleport to users' homes who have a * Geyser prefix

### ISSUE THREAD

**Issue by thiagogebrimm** [WiIIiam278/HuskHomes2#291]
I use geyser on my server and use "*" as a prefix, but I can't teleport to these players' homes

![image](https://user-images.githubusercontent.com/75040244/209601777-49286d76-c089-461e-b400-ca854e6cff0a.png)

**Comment by WiIIiam278** [comment]
Needs testing again with latest dev build

**Comment by ApliNi** [comment]
You can also change the prefix to ".", available in my server

**Comment by WiIIiam278** [comment]
The "." prefix is reserved due to being used to separate owners from home names in that format

If you'd like to see a config option to change that, file a ticket by all means :) This original issue should be fixed though afaik
