### ISSUE TITLE
`overwrite_homes_warps` feature fails if you have reached the home limit or don't have enough money

### ISSUE THREAD

**Issue by goflishMC** [WiIIiam278/HuskHomes2#293]
1. You do /sethome and it sets your home
2. If you do /sethome again, instead of setting the new location as your sethome it's telling me that I need to do /sethome name
3. If I try to do /sethome name it tells me I can only have 1 sethome because I already did /sethome the 1st time

I mentioned this on discord and was directed to post the issue on github.

The entire conversation: https://i.imgur.com/koMjFh0.png

**Comment by WiIIiam278** [comment]
Fixed in #323

**Comment by WiIIiam278** [comment]
Not fixed, apparently. Reopening
