### ISSUE TITLE
Economy actions do not withdraw money

### ISSUE THREAD

**Issue by Xenovac** [WiIIiam278/HuskHomes2#305]
![image](https://user-images.githubusercontent.com/113558344/214278406-5eb2e0f2-384a-4a90-98c1-eaed34fa32a8.png)

**Comment by WuzzyLV** [comment]
I also share the same issue, for me however none of the vault functions work, I have made sure my user doesn't have the bypass permission I'm on Vault and EssentialsX

**Comment by Emibergo02** [comment]
what economy plugin are you using?
