### ISSUE TITLE
Add option to turn off Commodore

### ISSUE THREAD

**Issue by XHealthy** [WiIIiam278/HuskHomes2#309]
Lib called Commadore doesn't work with command disablers so players cant block for example "huskhomes:huskhomes:home" from tab completing.

**Comment by nhanledev** [comment]
+1 for this, I don't like where it spams a lot of commands with `huskhomes:` prefix while the whole server is hiding all name spaced commands.

**Comment by WiIIiam278** [comment]
done in #323
