### ISSUE TITLE
Add compatibility with Folia

### ISSUE THREAD

**Issue by Aitooor** [WiIIiam278/HuskHomes2#342]
Would it be possible to add support for Folia de Paper in HuskHomes?

Folia url: https://github.com/PaperMC/Folia

**Comment by WiIIiam278** [comment]
Maybe but too early right now as this needs testing

**Comment by Aitooor** [comment]
No problem, thank you very much

**Comment by Aitooor** [comment]
Have you been able to review this? It would be great for many game modes to give it support

Sorry if I'm heavy. Thanks ❤️

**Comment by WiIIiam278** [comment]
It's planned and will be tracked in this issue

**Comment by Aitooor** [comment]
Thanks 🙏

**Comment by Iotados** [comment]
Would it be a good idea to create similar issues on HuskSync and HuskTowns? Considering they'd both probably get some benefit from a Folia port and just as an easy redirect for anyone asking

**Comment by Aitooor** [comment]
Great, thanks for considering our requests. And start working so fast. We appreciate it very much [#372](https://github.com/WiIIiam278/HuskHomes2/pull/372)
