### ISSUE TITLE
Missing TELEPORTATION_COMPLETE sound in config file

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/HuskHomes2#343]
Hello,

I am trying to use the sound effects and notice that some sound settings are missing, and default config file which is generated from the plugin is still missing the `TELEPORT_REQUEST_RECEIVED` sound.

This is a reference: https://github.com/WiIIiam278/HuskHomes2/blob/b27e2cc2a8f5e0688eaa10d98b5a9b04ba49ab3e/common/src/main/java/net/william278/huskhomes/config/Settings.java#L144

Thank you.

**Comment by WiIIiam278** [comment]
Oh you're right, looks like I forgot to add it.
