### ISSUE TITLE
/back command permission does not work

### ISSUE THREAD

**Issue by nhanledev** [WiIIiam278/HuskHomes2#346]
Hello,

According to the docs at https://william278.net/docs/huskhomes/commands, the player only can access `/back` command if that user has permission `huskhomes.command.back`. But in the current build of HuskHome (v4.1.1), the plugin no longer check that permission anymore. It makes the command publicly available for everyone.

Edit: I also found this bug in other command like `phomelist` and the command can be executed without the documented permissions.

I am running HuskHomes on Paper 1.17.1 build 411

**Comment by nhanledev** [comment]
IMO the reason causes that effect is in this line:
https://github.com/WiIIiam278/HuskHomes2/blob/1bdf21dd7ddaa2f0b9c15818b14b9948d8447940/bukkit/src/main/java/net/william278/huskhomes/command/BukkitCommand.java#L105
What do you think?

**Comment by WiIIiam278** [comment]
`/back` is enabled by default to allow anyone to use it without having to install a permission plugin or op players. Set the `huskhomes.command.back` node to false to deny it for users. Closing as invalid.

**Comment by nhanledev** [comment]
OK because it is different than the old version so I thought it was a bug. I can totally deny the permission.

**Comment by WiIIiam278** [comment]
This hasn't changed since 3.x afaik
https://github.com/WiIIiam278/HuskHomes2/blob/10a3eebc5571af75e2fb14abc1afbd5595bb0bb4/common/src/main/java/net/william278/huskhomes/util/Permission.java#L153
