### ISSUE TITLE
Huskhomes phome chat GUI does not escape formating codes

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#35]
The base formating codes for the default game are used in the Chat GUI for the phones list (,to he assumed for warps GUI and Homes GUI too).

This leads to obfuscation, strike through, bolding etc when using certain characters in conjuction with symbols.

**Comment by WiIIiam278** [comment]
Inserting ampersand and other symbols as home names technically shouldn't be possible but is (from older versions and essentials). Issue is that we now minedown format home names rather than the proper insertion method

**Comment by WiIIiam278** [comment]
Postponing this one for now since its' a bit annoying and cumbersome to fix + only effective in very few circumstances

**Comment by WiIIiam278** [comment]
Not going to fix this as it makes customizing how homes appear in the menu impossible + this should only be a thing with a very small number of migrated homes.
