### ISSUE TITLE
Huskhomes won't enable & console error

### ISSUE THREAD

**Issue by RainbowTea** [WiIIiam278/HuskHomes2#378]
Error:
https://gist.github.com/RainbowTea/b99c350b58283a8e2cf6c2c70e1c8a54

Unsure why its not working. It randomly stopped working after the server froze due to another plugin and after rebooting the server huskhomes no longer works.

Running Paper version git-Paper-522 (MC: 1.19.4) 

Plugin Version: 4.2.1

**Comment by WiIIiam278** [comment]
This looks like a configuration issue. Specifically, it seems like you haven't setup plan correctly on your server, such as by not entering the server ID into plan's config. Try removing plan and observing if the issue persists. If it doesn't, try re-installing plan, deleting it's config files, and ensure it's on the latest version.

**Comment by WiIIiam278** [comment]
@RainbowTea Can you check the above and confirm if you are still experiencing this?

**Comment by WiIIiam278** [comment]
Caused by a circular dependency with the paper plugin, fixed as a result of #390

**Comment by RainbowTea** [comment]
> Caused by a circular dependency with the paper plugin, fixed as a result of #390

I'm so sorry for re-opening this but I believe the same error occurred again.
https://gist.github.com/RainbowTea/04660ffa3b09e7b9d062530d27ce7e41

running Paper version git-Paper-538 (MC: 1.19.4)

HuskHomes v4.3.1

Also, could you clarify what you meant last time by plan ID?
