### ISSUE TITLE
Implement HikariCP connection pooling

### ISSUE THREAD

**Issue by GuNanOvO** [WiIIiam278/HuskHomes2#40]
An error occurred when I tried to use MySQL to store data.
Output error message: [HuskHomes] The mySQL JBDC library is missing! Please download and place this in the /lib folder.
HuskHomes version 2.5. MySQL version 5.7.
![image](https://user-images.githubusercontent.com/63027311/120511264-d5bc6280-c3fc-11eb-8bbb-392df609317a.png)

**Comment by WiIIiam278** [comment]
Thanks for your report - please tell me what Java version you are using. I recently updated the driver to work with Java 11+ environments, so that might be the cause. If not, then you need to make sure you download the updated driver from  https://dev.mysql.com/downloads/connector/j/ and put this in your Java library folder (on Windows this is in `C:\Program Files (x86)\Java\<java version you are using>\lib\`)

**Comment by GuNanOvO** [comment]
I use OpenJDK11. My server did not install OpenJDK on the host for easy transfer. I downloaded the OpenJDK11 portable zip package from https://bell-sw.com/ and unzipped it to a separate folder. When starting the server, the OpenJDK path is specified separately to start. Just now I downloaded mysql-connector-java-8.0.25.jar from https://dev.mysql.com/downloads/connector/j/ and placed it in `OpenJDK/lib/`, and then tried to start the server, the plug-in still does not work .My English is not very good, I use Google Translate, hope you forgive me.

**Comment by WiIIiam278** [comment]
I'm very sorry - but I am not totally certain what the cause of the issue is. 
I would recommend upgrading to Java 16 because Mojang will require it soon and not use the Liberica OpenJDK but perhaps the Oracle JDK https://www.oracle.com/java/technologies/javase-jdk16-downloads.html - why is it that you are wanting to use a separate java installation for Minecraft rather than installing it standard on your OS?
What operating system are you using - Windows? If so, you should use the mySQL installer to install the drivers which may be a more direct way of doing it - although this will do it system wide and it seems you want to install it into a separate folder..

**Comment by GuNanOvO** [comment]
thanks for your help. The problem was not solved. But I'm exhausted, and I plan to think of a solution later. Your plugin looks great, although I can't use it, haha. Maybe you can be like other developers, most of the plugins that use MySQL to store data are working properly on my server.

**Comment by WiIIiam278** [comment]
My apologies again - the reason other plugins probably work is because they
utilise HikariCP connection pooling whereas I do it directly with the
driver. In the vast majority of cases this is fine as the JDBC connection
library comes standard with the installation of Java on the machine. In
your case, however, this is not what’s happened. This is something I’d like
to look into soon. I’m going to refocus this issue to track the
implementation of connection pooling which may have some other benefits to
it. Thank you and I am sorry it didn’t work out right away :)

**Comment by GuNanOvO** [comment]
too crazy! I tried to unzip the ‘mysql-connector-java-8.0.25.jar’ package into the plug-in ‘HuskHomes-2.5.jar’ package and save it. Surprisingly, it has no errors and no longer prompts "The mySQL JBDC library is missing! Please download and place this in the /lib folder."Haha. Is it okay to do this? Will there be any hidden errors?

**Comment by WiIIiam278** [comment]
> too crazy! I tried to unzip the ‘mysql-connector-java-8.0.25.jar’ package into the plug-in ‘HuskHomes-2.5.jar’ package and save it. Surprisingly, it has no errors and no longer prompts "The mySQL JBDC library is missing! Please download and place this in the /lib folder."Haha. Is it okay to do this? Will there be any hidden errors?
> Just now, I checked my database. The plug-in successfully created the data table!

Haha, that's a really interesting one.. I guess it should work fine!?

**Comment by WiIIiam278** [comment]
Hey @GuNanOvO - Sorry for the tag, wanted to let you know that the latest versions of HuskHomes ensure that the mysql connector library is present at runtime using the spigot library install feature (especially since apparently some JDK 16's don't come with this by default unlike JDKs for 1.8)

**Comment by GuNanOvO** [comment]
Great, now the plugin will automatically download the MySQL connector library and it works fine. Thank you for reminding me. You are a great developer. <3

**Comment by GuNanOvO** [comment]
I don’t want to open another question, so I’m here to give you feedback. When I use the command: /home, HomeGUI should be opened under normal circumstances, but now there is an accident.
`[15:02:22 WARN]: [HuskHomesGUI] Plugin HuskHomesGUI v1.01 generated an exception while executing task 16153
java.lang.NullPointerException: Cannot invoke "me.william278.huskhomes2.data.SQL.Database.getConnection()" because "me.william278.huskhomes2.HuskHomes.database" is null
        at me.william278.huskhomes2.HuskHomes.getConnection(HuskHomes.java:63) ~[?:?]
        at me.william278.huskhomes2.api.HuskHomesAPI.getConnection(HuskHomesAPI.java:25) ~[?:?]
        at me.william278.huskhomes2.api.HuskHomesAPI.getHomes(HuskHomesAPI.java:102) ~[?:?]
        at com.technovision.HuskHomesGUI.playerdata.HuskHomesReader.<init>(HuskHomesReader.java:17) ~[?:?]
        at com.technovision.HuskHomesGUI.gui.HomeGUI.<init>(HomeGUI.java:29) ~[?:?]
        at com.technovision.HuskHomesGUI.events.HomeEvents.lambda$onCommandPreProcess$1(HomeEvents.java:105) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"a9394b8"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"a9394b8"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"a9394b8"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]`
After updating HomeGui, I did not use the plug-in in time. This problem has not been discovered until now, and it was normal before the update.
I am using OpenJDK16 and paper1.17. The link between the HoskHomes plug-in and the database is normal.

**Comment by WiIIiam278** [comment]
> I don’t want to open another question, so I’m here to give you feedback. When I use the command: /home, HomeGUI should be opened under normal circumstances, but now there is an accident.
> `[15:02:22 WARN]: [HuskHomesGUI] Plugin HuskHomesGUI v1.01 generated an exception while executing task 16153 java.lang.NullPointerException: Cannot invoke "me.william278.huskhomes2.data.SQL.Database.getConnection()" because "me.william278.huskhomes2.HuskHomes.database" is null at me.william278.huskhomes2.HuskHomes.getConnection(HuskHomes.java:63) ~[?:?] at me.william278.huskhomes2.api.HuskHomesAPI.getConnection(HuskHomesAPI.java:25) ~[?:?] at me.william278.huskhomes2.api.HuskHomesAPI.getHomes(HuskHomesAPI.java:102) ~[?:?] at com.technovision.HuskHomesGUI.playerdata.HuskHomesReader.<init>(HuskHomesReader.java:17) ~[?:?] at com.technovision.HuskHomesGUI.gui.HomeGUI.<init>(HomeGUI.java:29) ~[?:?] at com.technovision.HuskHomesGUI.events.HomeEvents.lambda$onCommandPreProcess$1(HomeEvents.java:105) ~[?:?] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.17.jar:git-Paper-"a9394b8"] at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.17.jar:git-Paper-"a9394b8"] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.jar:git-Paper-"a9394b8"] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?] at java.lang.Thread.run(Thread.java:831) [?:?]`
> After updating HomeGui, I did not use the plug-in in time. This problem has not been discovered until now, and it was normal before the update.
> I am using OpenJDK16 and paper1.17. The link between the HoskHomes plug-in and the database is normal.

Hi there,
I'm aware of this issue and have opened an issue to track it: #54
Thanks
