### ISSUE TITLE
Pl3xMap hook does not account for reload

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [WiIIiam278/HuskHomes2#409]
Log: https://paste.ubuntu.com/p/qW7HyPqyvH/
Steps to reproduce: Use the command /pl3xmap reload to trigger this error, and the phome icon on the web side will disappear (or the error/404 icon will be displayed)

**Comment by WiIIiam278** [comment]
Likely caused because Pl3xMap clears the icon registry on reload. I assume Pl3xMap has a callback for this, so probably just a minor update needed to reload the icons on reload.
