### ISSUE TITLE
The conveyor system determines the jam

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [WiIIiam278/HuskHomes2#412]
![QQ图片20230523201339](https://github.com/WiIIiam278/HuskHomes2/assets/71379165/83b54955-2149-42f4-9baf-2aa7b492545d)

Not any err logs, Some players will get this error after teleporting, without warning, and can only temporarily fix this problem by exiting the game and re-entering

**Comment by WiIIiam278** [comment]
Sorry, I don't understand this error. Please clearly outline:
- What error players are encountering in-game, in English
- Steps to reproduce the error, including what happens before, during and after the error occurs
- Steps to mitigate the error
- Details surrounding your setup (database type, cross-server mode & message broker if you are using cross-server mode)
