### ISSUE TITLE
Please wait your current teleport finish

### ISSUE THREAD

**Issue by NeviskDOBLOCO** [WiIIiam278/HuskHomes2#413]
Several players are receiving the message "Please wait your current teleport finish" when trying to perform any type of teleport, the problem is more intense at event times since several players using /warp events at the same time.

Temporary solution that we are using to solve it is to use /tphere <player> so that he "bypasses" this pending teleport...

**Comment by welove69** [comment]
This issue still exists
HuskHomes4.5.3
1.20.1  Use mysql links
This can be solved by restarting the server
