### ISSUE TITLE
this is a bug

### ISSUE THREAD

**Issue by DCE-114514** [WiIIiam278/HuskHomes2#419]
hey bro
I'm sorry to bother you, but there's something wrong with him again ![27edef205d795f75.jpg](https://github.com/WiIIiam278/HuskHomes2/assets/132117183/013324cd-6507-4d86-a585-ccd6d1e9eced)

**Comment by WiIIiam278** [comment]
Duplicate of https://github.com/WiIIiam278/HuskHomes2/issues/415.
Please don't open duplicate issues :)

**Comment by DCE-114514** [comment]
> Duplicate of https://github.com/WiIIiam278/HuskHomes2/issues/415.
> Please don't open duplicate issues :)

Dude, these two are different.

**Comment by WiIIiam278** [comment]
The two are the same underlying issue, which requires further investigation. You must be patient.
