### ISSUE TITLE
Server experiences slow ticks when a player RTP

### ISSUE THREAD

**Issue by foxii-cn** [WiIIiam278/HuskHomes2#455]
Can you help me identify the issue?
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/e4d45808-4533-4344-b14d-2d1b1f318ee4)
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/fb9e41cf-39cd-495e-8d41-ca463de956a4)

**Comment by foxii-cn** [comment]
<html>
<body>


environment | version
-- | --
Java | azul/prime:17
HuskHomes | 4.4.2-328ce26
Fabric | 0.14.21
Minecraft | 1.20.1


</body>
</html>

**Comment by foxii-cn** [comment]
Thank you very much!

**Comment by WiIIiam278** [comment]
Works As Intended — unfortunately generating chunks is expensive! Use the cool-downs feature and pregen terrain with a plugin like chunky.

**Comment by foxii-cn** [comment]
Can we reopen this ? @WiIIiam278

**Comment by WiIIiam278** [comment]
The fabric code for this is very similar to the code for /spreadplayers (even hooking into this iirc) -- can you confirm if this vanilla MC command causes such lag?

**Comment by foxii-cn** [comment]
> The fabric code for this is very similar to the code for /spreadplayers (even hooking into this iirc) -- can you confirm if this vanilla MC command causes such lag?

Thanks, I will do more test with /spreadplayers, /huskhomes:rtp and /essentialcommands rtp tomorrow(UTC+8). I will provide more details after that. Now I have to sleep : )

**Comment by foxii-cn** [comment]
Huskhomes(lag):
https://spark.lucko.me/rpicVEMiTl
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/421784ae-9652-43bf-b7fa-520ac82ca96d)
Huskhomes(better):
https://spark.lucko.me/RNUIouME9k
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/0024cd47-5035-474b-89f1-d6d7df4d54d0)
/spreadplayers:
https://spark.lucko.me/EmZKM82XPp
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/b3305709-f63e-475e-8cb4-14778f3d392b)
essentialcommands:
https://spark.lucko.me/6CzRWVPb3I
![image](https://github.com/WiIIiam278/HuskHomes/assets/38043552/45a50fc7-5bc4-4424-af76-8b923328a756)
@WiIIiam278

**Comment by foxii-cn** [comment]
I think I have found the reason. During several teleports that took a significant amount of time in Huskhomes, the cooldown checks also took a long time, almost as much as the actual teleportation time. I am using MySQL for data storage, but I believe the communication with MySQL should not occur in the main thread, as implied by its package name (nio). Is there an issue with that?

**Comment by WiIIiam278** [comment]
Does seem like some db logic is being done on the main thread when it shouldn’t be

**Comment by foxii-cn** [comment]
So are we going to reopen it?
