### ISSUE TITLE
RTP is not working for Geyser players, and no cooldown is being made in the database

### ISSUE THREAD

**Issue by kolderz** [WiIIiam278/HuskHomes2#460]
If Geyser players use /RTP, it will work for the first time but after that, they cannot use /RTP anymore, and no player cooldown data is created in the database.
Plugin version: 4.4.2-e86fd41, v4.4.1 
Server version:  Folia1.20.1
Geyser version: Geyser version 2.1.2-SNAPSHOT (git-master-872d7e3) 
Floodgate prefix: '*'

**Comment by WiIIiam278** [comment]
Probably due to duplicate UUIDs, an issue in 4.4.1.

If you updated from 4.4.1 to 4.4.2 and didn't regenerate your cooldowns table, this will continue to occur as I haven't added a migration there yet. DROP your cooldowns table after updating to 4.4.2/latest

**Comment by WiIIiam278** [comment]
Are you using a MySQL database?

**Comment by WiIIiam278** [comment]
Oh, well, can't quite think what that is, then. UUIDs must be consistent so unless this is the problem I'm not sure
feel free to investigate further yourself, I can't (/won't) have the capacity to test on geyser environments
