### ISSUE TITLE
Re-implement cross-server tab completion (Regression from 2.4.x)

### ISSUE THREAD

**Issue by msmanui** [WiIIiam278/HuskHomes2#47]
Hello, we've setup in 2 servers and the tab complete isnt working when i want to send tpa and he is on another server.. We have enable the feature on the config.-

**Comment by WiIIiam278** [comment]
Hi, this feature is currently disabled in version 1.5; it’s planned to return in the next version, 1.5.1. It was disabled during refactoring and will be reimplemented in a more optimised form soon.
I apologise for the temporary inconvenience- you’ll need to hold tight in the meantime.
