### ISSUE TITLE
Relocating homes and warps when using mySQL causes them to be deleted

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#5]
After Renaming a home from "EndermanFarm" to "EndRaiding" i went to change it's location, the Plugin then informed me that the home "does not exists". 

After checking the Home list i found the home had vanished from my list. Even after a re log it did not return, The only other change made latter to the other home was to another former home called "End" which i renamed to "EndermanFarm".

**Comment by WiIIiam278** [comment]
Seems to be caused by cascading deletions as a result of the foreign key constraints imposed by deleting the old home location off the location table, which causes the home to get deleted. Only an issue with servers using mySQL mode.
```java
public static void updateHomeLocation(String ownerName, String homeName, Location newLocation) {
        Integer playerID = getPlayerId(ownerName);
        deleteHomeTeleportLocation(playerID, homeName); 
        database.setHomeTeleportPoint(homeName, playerID, new TeleportationPoint(newLocation, HuskHomes.settings.getServerID()));
    }
