### ISSUE TITLE
Implement an FAQ section to Wiki documentation 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#53]
Implementation of a FAQ section to the Wiki subsection; this will include any questions that may crop up on occasion such as disabling a command via permissions or common questions on features. 

This section can be updated, changed and morphed per version and will be revised as such -- this means that if any drastic change is performed steps to reproduce or test can be found either in the section or within a external document. 

- [ ] Introduction to the FAQ
- [ ] Frequently Asked Questions: Permissions
- [ ] Frequently Asked Questions: Command Errors
- [ ] Frequently Asked Questions: Support

Hopefully this will both improve support efficiency and help new users.

**Comment by WiIIiam278** [comment]
Closing for now, will be worked on as part of 3.0
