### ISSUE TITLE
Home Description Support UTF-8

### ISSUE THREAD

**Issue by TreeHD** [WiIIiam278/HuskHomes2#67]
Hello
Is it possible to make Home Description support UTF-8?

Thanks
![image](https://user-images.githubusercontent.com/23317010/125339566-fd033980-e383-11eb-8d3f-598c9246f631.png)

**Comment by WiIIiam278** [comment]
Yep, i'll look into this for v2.7 - I didn't consider folks wanting to use nonlatin/unicode characters in these but it's a fair point and will be fixed.
