### ISSUE TITLE
Message Error

### ISSUE THREAD

**Issue by SnivyJ** [WiIIiam278/HuskHomes2#72]
Plugins Version HuskHomes 2.6.3

when i use 
 language: 'zh-tw'
The plugins generates a 1KB document  whit nothing message data
![image](https://user-images.githubusercontent.com/25428011/125794140-88d8f82e-e489-45b4-9849-af4851cf5694.png)
![image](https://user-images.githubusercontent.com/25428011/125794210-48c18798-b80d-4503-bec4-243ad88af6f9.png)

I try to translate a message file in simplified Chinese with an en-gb document,
The translation of documents is not comprehensive, some of them are changed to simplified Chinese, and some of them are still in English
![image](https://user-images.githubusercontent.com/25428011/125794881-4ab35ad7-1206-4373-be15-15e51dfdc570.png)
![image](https://user-images.githubusercontent.com/25428011/125794907-3ffe2ff8-dcee-41da-8796-69468ccca5b2.png)
![image](https://user-images.githubusercontent.com/25428011/125794946-8a89bcb8-7cf2-4ff6-b27f-31202797ed94.png)
![image](https://user-images.githubusercontent.com/25428011/125794972-eb51711c-48eb-4100-9cbf-44e299af5e26.png)

**Comment by WiIIiam278** [comment]
Since you've closed the issue, I assume you have corrected the problem, but this looks like another plugin was generating those messages as a result of a command conflict. You can uninstall the plugin or make use of commands.yml aliases to override command defaults.
