### ISSUE TITLE
HuskHomes Addon: Warp Portals/Signs

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#75]
>Warp Portals and Signs -- premium? -- Addon plugin definitely it's a un-needed feature in a base plugin that is primarly >"homes and exploration aid".
>
Original Suggestion by "Melonzio"

Postponed until it can further fleshed out.

**Comment by Iotados** [comment]
Status has been bumped up to medium

**Comment by WiIIiam278** [comment]
Closing as out of scope for now
