### ISSUE TITLE
HuskHomes GUI: Full GUI support

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#77]
> Warps, Homes, Phomes with GUI support. /tpa included with a GUI showing all players (Bungee support)
>
Original suggestion by "Melonzio"

**Comment by Iotados** [comment]
Forgot to remove the postponed bit

**Comment by WiIIiam278** [comment]
I don't like GUI work but I found a nice library for this one that will work well. Will need to rewrite HuskHomesGUI most likely in entirety, though, but that's probably a good thing.

**Comment by WiIIiam278** [comment]
done in 2.1
