### ISSUE TITLE
/back History 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#78]
For use in admin position tracking for damage control. A /back history command with a permission node (huskhomes.back.history?) to view players previous 3/5/10... /backs locations.

_/backhistory <user>_

on click/hover it should auto-fill and execute a tp command to the location and for safety block damage for X seconds (perhaps a config option?).

**Comment by WiIIiam278** [comment]
This feature wouldn't be impossible but honestly seems far too involved to be worth the hassle and not actually incredibly useful. Closing as rejected for now, if there's significant demand it can be revisited.

**Comment by Uharn** [comment]
i would also be interrested because i have many scenario where the last /back is not the good one because something wrong happenned (for example RTPing to another bungeeserver)

**Comment by WiIIiam278** [comment]
Thanks for the feedback - A shame that there's other plugins causing you issue, I think adding back history here though would be more of a band-aid on the wider problem to be honest, though.
