### ISSUE TITLE
Look into Spectator action bar tp blocking

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#80]
Potentially add in a new permission:
Huskhomes.spectator.tp

That would manage spectator action bar tping, this may be a niche case but thus ability may prove handy for creative, plot and large scale servers who want to respect player privacy by limiting who can use such a feature. 

It is unclear how you might be able to implement this and if this is possible so marked without priority to reflect that.

**Comment by WiIIiam278** [comment]
out of  scope
