### ISSUE TITLE
/tp forgetting world dimension 

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#83]
![iEaO7o2](https://user-images.githubusercontent.com/76396089/129493541-1925d48c-2e10-46ec-8f95-1c283a7646b2.png)

> but, after I do it with the world, the next time I do that command I don't have to put the world name. it's like it somehow doesn't know where I'm at

**Comment by WiIIiam278** [comment]
Closing as cannot reproduce
