### ISSUE TITLE
The teleport name autocompletition usually fails.

### ISSUE THREAD

**Issue by Miky88** [WiIIiam278/HuskHomes2#84]
Hi I'm a Developer on a server with many members online.

In this server there are often users with a similar name, I'll use `Gabriel` and `Gabriel_17` on the following example.

The problem here is that when i do `/tpa Gabriel` the request is sent to `Gabriel` but when he accepts the request the other guy is teleported instead, or in some other scenarios the request is sent to `Gabriel_17` directly.

**Comment by WiIIiam278** [comment]
Duplicate of #71
