### ISSUE TITLE
Allow /tp commands to be run via console

### ISSUE THREAD

**Issue by msmanui** [WiIIiam278/HuskHomes2#92]
Hi there!

Adding support to **TP** command to be executed through the console.

Also support pitch and yaw -> /tp x y z pitch yaw world server PlayerName

**Comment by Esronn** [comment]
Yes please! This is exactly what we need

**Comment by Iotados** [comment]
Considering the amount of times this is asked at this point, getting it implemented seems logical thus the increase in priority
