### ISSUE TITLE
Add PAPI formatting support in language files

### ISSUE THREAD

**Issue by Iotados** [WiIIiam278/HuskHomes2#96]
Add PAPI support within the language files, fairly self explanatory...

**Comment by Iotados** [comment]
Amended because even staff can be clueless to how things work

**Comment by WiIIiam278** [comment]
I'm definitely not against adding this, but am not sure of a great use case for this. Either way, I think when this happens the the PlaceholderAPI integration should be added to the main plugin rather than as a PAPI extension

**Comment by WiIIiam278** [comment]
Not planned for now
