### ISSUE TITLE
Add option (default false) for /back position setting on teleport event

### ISSUE THREAD

**Issue by GuNanOvO** [WiIIiam278/HuskHomes2#97]
The command /back can record the last return point in most cases, but when I use the BetterRTP plug-in for random tp, it will not record the last return point. I haven't done too many other plug-in /tp tests. However, it may be possible to optimize the detection of the last point of change, compatible with more plug-ins, and more perfect /back.

**Comment by WiIIiam278** [comment]
Setting /back based on the teleport event (e.getFrom) was a feature of HuskHomes 1.5.x, so this is technically a bit of a feature regression, it can be looked into though it's worth noting this is something that can often break compatibility with stuff like the Citizens plugin and other plugins that spoof players with packets, so it'd be good as an option that is off by default.

**Comment by WiIIiam278** [comment]
Going to close this for the above reasons; incompatibility & issues; following further thoughts
